---
title: "Music Insights"
author: Jay Gohner
output: html_notebook
---

First, we need to import tidyverse to handle data manipulation

```{r}
library("tidyverse")

survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")
preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")

```

Now, we will rename the column names for survey
```{r}
colnames(survey)[colnames(survey) == "Timestamp"] <-"time_submitted"
colnames(survey)[colnames(survey) == "First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <-"pseudonym_generator"
colnames(survey)[colnames(survey) == "What is your pseudonym?"] <-"pseudonym"
colnames(survey)[colnames(survey) == "Sex"] <-"sex"
colnames(survey)[colnames(survey) == "Major"] <-"academic_major"
colnames(survey)[colnames(survey) == "Academic Year"] <-"academic_level"
colnames(survey)[colnames(survey) == "Year you were born (YYYY)"] <-"year_born"
colnames(survey)[colnames(survey) == "Which musical instruments/talents do you play? (Select all that apply)"] <-"instrument_list"
colnames(survey)[colnames(survey) == "Artist"] <-"favorite_song_artist"
colnames(survey)[colnames(survey) == "Song"] <-"favorite_song"
colnames(survey)[colnames(survey) == "Link to song (on Youtube or Vimeo)"] <-"favorite_song_link"

```

First we create a Person and FavoriteSong tables
```{r}
library(dplyr)
library(tidyr)
library(readr)

Person <- tibble(time_submitted=survey$time_submitted, pseudonym=survey$pseudonym, pseudonym_generator=survey$pseudonym_generator, sex=survey$sex, academic_major = survey$academic_major, academic_level=survey$academic_level, year_born=survey$year_born)

FavoriteSong <- tibble(pseudonym=survey$pseudonym, song=survey$favorite_song, artist=survey$favorite_song_artist, link=survey$favorite_song_link)

Person$time_submitted <- as.POSIXlt(parse_datetime(Person$time_submitted, format="%m/%d/%y %H:%M"))

```


```{r}
Person$academic_level <- as.factor(Person$academic_level)
Person$academic_major <- as.factor(Person$academic_major)
levels(Person$academic_level)
levels(Person$academic_major)
```

```{r}
levels(Person$academic_major)[levels(Person$academic_major) == "Computer information systems"] <- "Computer Information Systems"
levels(Person$academic_major)
```

Creating a new table Ratings, from preferences
```{r}
Ratings <- gather(preferences, artist_song, rating, 3:45)

```